### ISSUE TITLE
Group stops playing when one CC is powered off

### ISSUE THREAD

**Issue by erkr** [music-assistant/hass-music-assistant#102]
Hi. 
I have configured 3 CC's as a group 'everywhere'.
Starting a Cast to the group, while one of the CC's is powered on afterwards, works great (automatically starts playing as well)
Powering off of one of the CC's interrupts the CAST with this error: 
```
Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.9/site-packages/pychromecast/socket_client.py:396 
First occurred: 20:49:05 (2 occurrences) 
Last logged: 21:18:15

[Everywhere_57([::ffff:c0a8:b220]):32034] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:b220]', 32034)), retrying in 5.0s
[Audio57Serre([::ffff:c0a8:b220]):8009] Failed to connect to service ServiceInfo(type='host', data=('[::ffff:c0a8:b220]', 8009)), retrying in 5.0s
```
Definitely an edge case 🤔, 
Best
Eric

**Comment by marcelveldt** [comment]
Use the "mute as power" to workaround that. Chromecast devices do not have a real power control.
Instead when you send turn off in HA, the current running app is stopped, causing the behavior you're seeing.

In the integration options I've implemented an option to select your Chromecast (client) players to have mute as powercontrol. That way you can toggle a player on/off while the group keeps playing.

Kers op de taart: If you turn off the last player in the group, the group is powered off/stopped.

**Comment by erkr** [comment]
Hi Marcel
I saw that mute option but didn't use it. In my setup I physically power off the CC's using power plugs. 
In MASS the raw Google cast entities are imported. For control I used universal media players to embed the exported mass_* players and route the power controls (turn on/off) to these plugs.
So, the CC's simply drop off the grid 😅
Below one of the universal media player configurations.
Best 
Eric
```
  - platform: universal
    name: Serre
    children:
      - media_player.mass_audio57serre
    commands:
      turn_on:
        service: light.turn_on
        target:
          entity_id: light.speakers
      turn_off:
        service: light.turn_off
        target:
          entity_id: light.speakers
      volume_up:
        service: media_player.volume_up
        data:
          entity_id: media_player.mass_audio57serre
      volume_down:
        service: media_player.volume_down
        data:
          entity_id: media_player.mass_audio57serre
      volume_set:
        service: media_player.volume_set
        data_template:
          entity_id: media_player.mass_audio57serre
          volume_level: '{{ volume_level }}'
      volume_mute:
        service: media_player.volume_mute
        data:
          entity_id: media_player.mass_audio57serre
          is_volume_muted: '{{ is_volume_muted }}'
    attributes:
      state: light.speakers
    device_class: speaker
```
