### ISSUE TITLE
Title and thumbnail from a radio station is not displayed on a Google Nest Hub (2. Gen)

### ISSUE THREAD

**Issue by mgraebi** [music-assistant/hass-music-assistant#1074]
### What version of Music Assistant has the issue?

2022.12.1

### The problem

The title and thumbnail from a radio station is not displayed on a Google Nest Hub (2. Gen).
My Script-Code:
```
service: media_player.play_media
target:
  entity_id: media_player.mass_allen_boxen
data:
  media_content_id: media-source://mass/database://radio/4
  media_content_type: audio/flac
metadata:
  title: JAM FM
  thumbnail: >-
    https://images.weserv.nl/?w=200&url=http://cdn-profiles.tunein.com/s136277/images/logoq.png
  media_class: music
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://mass
    - media_content_type: music
      media_content_id: media-source://mass/radio
```

In my opinion the code is missing the extra lines:
```
data:
  extra:
    thumb: 
    title: 
```

### How to reproduce

Create a script via the UI with radio station

### Additional information

```
data:
  media_content_id: 
  media_content_type: 
  extra:
    thumb: 
    title: 
```

### What version of Home Assistant Core are your running

2023.1.5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Is this what you are asking for? https://github.com/music-assistant/hass-music-assistant/issues/300

**Comment by mgraebi** [comment]
Yes, it sounds like the same problem. But i already use the mass entity. The Hub shows only: Default Media Receiver ...
With 
```
data:
  extra:
    thumb: 
    title: 
```
it works.

**Comment by OzGav** [comment]
Ok haven’t you found the solution then? (Which is great btw if you have)

**Comment by mgraebi** [comment]
No, i haven't found the solution.
When i use
```
service: media_player.play_media
data:
  media_content_id: media-source://radio_browser/962a1121-0601-11e8-ae97-52543be04c81
  media_content_type: music
  enqueue: replace
  extra:
    thumb: http://www.jam.fm/assets/icons/apple-touch-icon.png
    title: Jam FM
target:
  entity_id: media_player.allen_boxen

```
it works.

When i use
```
service: media_player.play_media
target:
  entity_id: media_player.mass_allen_boxen
data:
  media_content_id: media-source://mass/database://radio/4
  media_content_type: audio/flac
metadata:
  title: JAM FM
  thumbnail: >-
    https://images.weserv.nl/?w=200&url=http://cdn-profiles.tunein.com/s136277/images/logoq.png
  media_class: music
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://mass
    - media_content_type: music
      media_content_id: media-source://mass/radio
```
it doesn't work.

Wenn i use
```
service: media_player.play_media
target:
  entity_id: media_player.mass_allen_boxen
data:
  media_content_id: media-source://mass/database://radio/4
  media_content_type: audio/flac
  extra:
    thumb: http://www.jam.fm/assets/icons/apple-touch-icon.png
    title: Jam FM
metadata:
  title: JAM FM
  thumbnail: >-
    https://images.weserv.nl/?w=200&url=http://cdn-profiles.tunein.com/s136277/images/logoq.png
  media_class: music
  children_media_class: null
  navigateIds:
    - {}
    - media_content_type: app
      media_content_id: media-source://mass
    - media_content_type: music
      media_content_id: media-source://mass/radio
```
it doesn't work either.

In my opinion, the problem is with the "mass" entity.
