### ISSUE TITLE
Impossible to start track to filesystem_smb

### ISSUE THREAD

**Issue by fliespl** [music-assistant/hass-music-assistant#1284]
### What version of Music Assistant has the issue?

v2

### The problem

I am downloading mp3's to my OMV instance which is attached as remote fileysystem.

Then in my automation I am trying to start this track using:

```
          - service: mass.queue_command
            data:
              player_id: media_player.mass_nest_salon
              uri: filesystem_smb://track/{{ states('input_text.youtube_mp3') }}
              command: play_media
              enqueue_mode: replace
```

It fails with:
Invalid uri: filesystem_smb://track/KtT64JFNgvo.mp3

And in system log:
```
Pobieranie youtube i puszczanie: Choose at step 1: choice 1: Error executing script. Unexpected error for call_service at pos 5: artist://sanah not found on provider filesystem_smb
```

I am not mentioning artist anywhere - a bug might be related to other issue I have created (about not possible to browse MASS media).

### How to reproduce

Described my setup in "the problem" section.

### Relevant log output

Error executing script. Unexpected error for call_service at pos 5: artist://sanah not found on provider filesystem_smb

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative
