### ISSUE TITLE
It is not possible to install on a server installed on a docker version of the pi

### ISSUE THREAD

**Issue by Roei639** [music-assistant/hass-music-assistant#1287]
### What version of Music Assistant has the issue?

latest

### The problem

When trying to install the Music Assistant server using docker on a pi4, an error is received:
no matching manifest for linux/arm/v8 in the manifest list entries

### How to reproduce

Docker installation on pi 4

### What version of Home Assistant Core are your running

2023.5.4

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi

**Comment by OzGav** [comment]
Are you running the 64bit version of the OS
.

**Comment by Roei639** [comment]
Yes.

**Comment by OzGav** [comment]
If you are using the latest tag that isn’t working. You need to try something  like 
`ghcr.io/music-assistant/server:latest@sha256:519de4ae6fd774646091a50014eb2da506daf1b0e2b8640e515a4046cbc56551`

**Comment by Roei639** [comment]
I managed to install, but the server does not work and the log is empty

**Comment by OzGav** [comment]
It takes a few minutes to start but if it isn’t working you will need to supply more info about log entries in MA and HA. Exactly what environment you are installing into and how. Whether the addon shows that it has started and whether it continues to show that it is running. Whether any error messages are shown when you attempt to open the UI. Screenshots can help.

**Comment by Roei639** [comment]
1. Installed in docker on pi4
2. The docker is active but not working
3. The docker log is empty
4. Trying to access the MA interface using address 192.168.1.253:8095 and there is no access, does not work.
5. I didn't get to the stage of connecting to HA, so the log is not relevant
6. 
![Screenshot_20230606_004817_Chrome](https://github.com/music-assistant/hass-music-assistant/assets/65112146/b900f339-0242-400e-9d6f-32f4e76619a0)

**Comment by OzGav** [comment]
How much RAM have you allocated to the container? You need 2GB minimum

**Comment by Roei639** [comment]
The container is not limited.  There is 7GB RAM available
```
music-assistant-server:
    container_name: music-assistant-server
    image: ghcr.io/music-assistant/server:latest@sha256:519de4ae6fd774646091a50014eb2da506daf1b0e2b8640e515a4046cbc56551 # <<< Desired release version here
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - /home/pi/docker/docker-mounts/music-assistant-server/data:/data/
      - /home/pi/docker/docker-mounts/ha/media:/media-ha/
```
