### ISSUE TITLE
[frontend] vuetify config file is misused to load global styles, causing lots of duplicated styles

### ISSUE THREAD

**Issue by Sirs0ri** [music-assistant/hass-music-assistant#1443]
### What version of Music Assistant has the issue?

music-assistant/frontend 2.0.11

### The problem

The vuetify config file loaded through the [vite config](https://github.com/music-assistant/frontend/blob/main/vite.config.ts#L22) is currently used to [load the full content](https://github.com/music-assistant/frontend/blob/main/src/styles/settings.scss#L12) of the global.css stylesheet, and the styles from '@egjs/vue3-flicking`. 

It's not intended to do this ([vuetify docs](https://vuetifyjs.com/en/features/sass-variables/#duplicated-css)) as this leads to a copy of these styles being injected into every single component, causing lots of duplicated code.

A preferred solution for loading styles globally would for example be to load them in the [App.vue](https://github.com/music-assistant/frontend/blob/main/src/App.vue) file, or through a css loader configured in vite.

The frontend currently loads ~900KB just stylesheets on the settings page, a lot of which is just duplicated code.

### How to reproduce

Look at any component through your browser's dev-tools and you'll notice, there's the following style defined over and over: 

```css
* {
    -webkit-user-drag: none;
    -khtml-user-drag: none;
    -moz-user-drag: none;
    -o-user-drag: none;
    user-drag: none;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

This is a part of [global.css](https://github.com/music-assistant/frontend/blob/main/src/styles/global.css#L38-L50) that's imported into every file through the vuetify settings as described above.

![image](https://github.com/music-assistant/hass-music-assistant/assets/6765536/ec9221af-28ff-4f60-aebd-3e13b35506ef)

### What version of Home Assistant Core are your running

n.a.

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Raspberry Pi
