### ISSUE TITLE
Wrong playing media title shown

### ISSUE THREAD

**Issue by xteaun** [music-assistant/hass-music-assistant#1641]
### What version of Music Assistant has the issue?

2023.6.0b6

### The problem

I call the following service with a custom sentence trigger:

```
service: mass.play_media
data:
  media_type: artist
  media_id: "{{trigger.slots.artist}}"
  artist: "{{trigger.slots.artist}}"
target:
  entity_id: xxxx
```
Music assistant then plays tracks by the correct artist. But the media title attribute of the state of the music assistant media_player entity is wrong. The very first track is shown correctly. But from the second track on it always shows the media title of the song that has played before the current song. This also goes for the UI. 

### How to reproduce

Call this service:

```
service: mass.play_media
data:
  media_type: artist
  media_id: Udo Lindenberg
  artist: Udo Lindenberg
target:
  entity_id: xxxx
```

### What version of Home Assistant Core are your running

2023.11.2

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi
