### ISSUE TITLE
Music Assistant only plays finite number of tracks by any artist

### ISSUE THREAD

**Issue by xteaun** [music-assistant/hass-music-assistant#1658]
### What version of Music Assistant has the issue?

2.0.0b75

### The problem

When I ask Music Assistant to play music by any artist with Spotify, it will only play a finite number of songs by that artist. But Spotify will keep playing an infinite number of songs by that artist.

### How to reproduce

Call this service:

```
service: mass.play_media
data:
  media_type: artist
  media_id: Queen
target:
  entity_id: media_player.hauptschlafzimmer
```

### What version of Home Assistant Core are your running

2023.11.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi
