### ISSUE TITLE
mass.search media_type radio is not working from release 2024.1.0b2

### ISSUE THREAD

**Issue by lor74** [music-assistant/hass-music-assistant#1755]
### What version of Music Assistant has the issue?

2.0.0b79

### The problem

I use mass search to get artist info using the media_type: radio (an option reported in the documentation).
From last two update it doesn't work... but it still works with other options suc as playlist.

### How to reproduce

```
service: mass.search
data:
  name: personal jesus
  media_type: radio
  artist: Depeche Mode
  limit: 5
```

### Relevant log output

In the log (in dubug mode) the only related entry is:
`2024-01-03 09:50:55.296 DEBUG (MainThread) [music_assistant.webserver] [547762212624] Handling command music/search`

### What version of Home Assistant Core are your running

2024.1.0b5

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
media type radio ? 
That is really strange!

If you want to fetch track info, you have to use the media_type track here

**Comment by lor74** [comment]
With 2023 package it works... 

```
service: mass.search
data:
  name: Depeche Mode
  media_type: radio
  limit: 1
```

Response:

```
artists:
  - media_type: artist
    item_id: 762310PdDnwsDxAQxzQkfX
    provider: spotify
    name: Depeche Mode
    external_ids: []
    sort_name: depeche mode
    uri: spotify://artist/762310PdDnwsDxAQxzQkfX
  - media_type: artist
    item_id: "47445"
    provider: qobuz
    name: Depeche Mode
    external_ids: []
    sort_name: depeche mode
    uri: qobuz://artist/47445
albums: []
tracks: []
playlists: []
radio:
  - media_type: radio
    item_id: 163ec9a5-0f9c-11ea-a87e-52543be04c81
    provider: radiobrowser
    name: 80s80s Ddepeche Mode
    external_ids: []
    sort_name: 80s80s ddepeche mode
    uri: radiobrowser://radio/163ec9a5-0f9c-11ea-a87e-52543be04c81
    duration: 172800
```

I use to get the URI of the artist and then start a playlist with radio mod on...

```
  - service: mass.play_media
    target:
      device_id: e325948e0c54ba0b8ea12bbc6d11b162
    data:
      media_type: playlist
      media_id: "{{ uri_result.artists[0]['uri'] }}"
      radio_mode: "on"
```

**Comment by lor74** [comment]
Chenging radio with artist... imass.search shows the same result... I can't remember why I use radio instead of artist... (maybe I was using the prevoius release 2023.6.0b6

**Comment by OzGav** [comment]
You need to be more specific with your replies. What is the "same result"? Same as it used to work or same as what you did not include in your original post (you show your query but not the result?)

**Comment by lor74** [comment]
Sorry... 

With this version: 2023.12.0
The following search

```

service: mass.search
data:
  name: Depeche Mode
  media_type: artist
  limit: 1
```

produce

```
artists:
  - media_type: artist
    item_id: 762310PdDnwsDxAQxzQkfX
    provider: spotify
    name: Depeche Mode
    external_ids: []
    sort_name: depeche mode
    uri: spotify://artist/762310PdDnwsDxAQxzQkfX
  - media_type: artist
    item_id: "47445"
    provider: qobuz
    name: Depeche Mode
    external_ids: []
    sort_name: depeche mode
    uri: qobuz://artist/47445
albums: []
tracks: []
playlists: []
radio:
  - media_type: radio
    item_id: 163ec9a5-0f9c-11ea-a87e-52543be04c81
    provider: radiobrowser
    name: 80s80s Ddepeche Mode
    external_ids: []
    sort_name: 80s80s ddepeche mode
    uri: radiobrowser://radio/163ec9a5-0f9c-11ea-a87e-52543be04c81
    duration: 172800
```
And if I use radio as media_type instead of artist

```
service: mass.search
data:
  name: Depeche Mode
  media_type: radio
  limit: 1
```

Response is quite similar

```
artists: []
albums: []
tracks: []
playlists:
  - media_type: playlist
    item_id: 4O86CiW7QkmKfF0xLDDUKD
    provider: spotify
    name: "Depeche Mode - Best Of "
    external_ids: []
    sort_name: depeche mode - best of
    uri: spotify://playlist/4O86CiW7QkmKfF0xLDDUKD
    owner: Toddy 101
    is_editable: false
  - media_type: playlist
    item_id: "3091655"
    provider: qobuz
    name: Depeche Mode
    external_ids: []
    sort_name: depeche mode
    uri: qobuz://playlist/3091655
    owner: qobuz.it
    is_editable: false
radio:
  - media_type: radio
    item_id: 163ec9a5-0f9c-11ea-a87e-52543be04c81
    provider: radiobrowser
    name: 80s80s Ddepeche Mode
    external_ids: []
    sort_name: 80s80s ddepeche mode
    uri: radiobrowser://radio/163ec9a5-0f9c-11ea-a87e-52543be04c81
    duration: 172800
```
With the latest beta release media_type radio doesn't work on the request 

```
service: mass.search
data:
  name: Depeche Mode
  media_type: radio
  limit: 1
```

Thanks
