### ISSUE TITLE
mass.search media type and limit not being respected

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#1953]
### What version of Music Assistant has the issue?

2.0.0.b103

### What version of the Home Assistant Integration have you got installed?

2024.2.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using the mass.search service call three problems are noted.
1) Radio results are always returned regardless of what is selected in the media type options
2) The LIMIT is not respected for albums or tracks
3) When using a local provider ONLY then doing a search with no media_id specified only returns the artist and no tracks. However, when streaming providers are available then all the fields are returned. For example this is returned with no streaming providers:

![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/2c43e010-f136-4ee3-9681-4b70d5067006)

versus this with streaming providers: 
[search_results.txt](https://github.com/music-assistant/hass-music-assistant/files/15145340/search_results.txt)

### How to reproduce

Do this search and observe multiple tracks and albums and a radio station returned

```
service: mass.search
data:
  limit: 1
  name: Test
  media_type:
    - album
    - track
```

Or do this search with only a local provider to see the result shown in the image above

```
service: mass.search
data:
  limit: 5
  name: Billy Joel
```

### Music Providers

Local files, Spotify, TuneIn, Radiobrowser

### Player Providers

Not used 

### What version of Home Assistant Core are your running

2024.2.0

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi

**Comment by marcelveldt** [comment]
fixed in b146 + HA integration 2024.5.0

**Comment by OzGav** [comment]
This is working well except tracks are not respecting the limit

```
service: mass.search
data:
  limit: 1
  name: john
```

[search.txt](https://github.com/music-assistant/hass-music-assistant/files/15242249/search.txt)
