### ISSUE TITLE
Dax88 - 8 Zone Player

### ISSUE THREAD

**Issue by fin05** [music-assistant/hass-music-assistant#1982]
### What version of Music Assistant has the issue?

2.0.0.b106

### What version of the Home Assistant Integration have you got installed?

2024.3.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I see the Dax player itself but I cant select individual  zones - I have each zone installed as a media_player entity in home assistant  - Music assistant can not see the zones that are entities.  Is there a way to expose them to Music Assistant?

### How to reproduce

no steps needed

### Music Providers

Spotify and youtube

### Player Providers

Airplay 
Home Assistant
Cast
DLNA

### What version of Home Assistant Core are your running

2024.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by OzGav** [comment]
Have you read our docs?

**Comment by fin05** [comment]
I didnt see anything about zone players

**Comment by OzGav** [comment]
Well there is on the troubleshooting page. However I think you actually want to expose the HA media players as that is your question in your post. I am not sure why you haven’t been able to if you have read the docs. You don’t mention why you aren’t able to.

**Comment by fin05** [comment]
I guess I dont know how - I have tried everything to my knowledge

**Comment by OzGav** [comment]
https://music-assistant.io/integration/installation/

Look at the home assistant player provider section

**Comment by OzGav** [comment]
Do you have this workign now?

**Comment by fin05** [comment]
I have the Dax unit loaded but music assistant cannot control the zones - i have to go back to home assistant to turn zones on and off and control volume - I guess it is more of a feature request than a bug

**Comment by marcelveldt** [comment]
Well, I suppose each "zone player" does not accept a play media command ? Its more like a single player that accepts play media commands and you can then switch zones on/off ?

That is indeed something you need to solve with HA. Music Assistant can only send audio to the "master" player.
You could trick this btw if you make use of template/universal media players in HA

**Comment by fin05** [comment]
I tried that - I get a single entity called media_player.dax_zone_ma 
I do not get any actual zones - there's no error showing

  - platform: universal
    name: Dax_Zones_MA
    unique_id: dax_zma
    children:
      - media_player.zone_16 #garage
      - media_player.zone_13 #patio
      - media_player.zone_11 #master_bedroom
      - media_player.zone_12 #master_bath
      - media_player.zone_14 #josh_office
      - media_player.zone_15 #cara_office
      - media_player.zone_17 #pool
      - media_player.zone_18 #living_room
    commands:
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room        
      turn_off:
        service: media_player.turn_off
        target:
          entity_id:
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_mute:
        service: media_player.mute
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      select_source:
        service: media_player.select_source
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          source: "{{ source }}"
      volume_set:
        service: media_player.volume_set
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          volume_level: "{{ volume_level }}"

**Comment by OzGav** [comment]
Can you just format that properly by highlighting all the YAML and press the <> button

**Comment by fin05** [comment]
`  - platform: universal
    name: Dax_Zones_MA
    unique_id: dax_zma
    children:
      - media_player.zone_16 #garage
      - media_player.zone_13 #patio
      - media_player.zone_11 #master_bedroom
      - media_player.zone_12 #master_bath
      - media_player.zone_14 #josh_office
      - media_player.zone_15 #cara_office
      - media_player.zone_17 #pool
      - media_player.zone_18 #living_room
    commands:
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room        
      turn_off:
        service: media_player.turn_off
        target:
          entity_id:
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_mute:
        service: media_player.mute
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      select_source:
        service: media_player.select_source
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          source: "{{ source }}"
      volume_set:
        service: media_player.volume_set
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          volume_level: "{{ volume_level }}"`

**Comment by fin05** [comment]
- platform: universal
    name: Dax_Zones_MA
    unique_id: dax_zma
    children:
      - media_player.zone_16 #garage
      - media_player.zone_13 #patio
      - media_player.zone_11 #master_bedroom
      - media_player.zone_12 #master_bath
      - media_player.zone_14 #josh_office
      - media_player.zone_15 #cara_office
      - media_player.zone_17 #pool
      - media_player.zone_18 #living_room
    commands:
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room        
      turn_off:
        service: media_player.turn_off
        target:
          entity_id:
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_mute:
        service: media_player.mute
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      select_source:
        service: media_player.select_source
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          source: "{{ source }}"
      volume_set:
        service: media_player.volume_set
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          volume_level: "{{ volume_level }}"``

**Comment by fin05** [comment]
```
  - platform: universal
    name: Dax_Zones_MA
    unique_id: dax_zma
    children:
      - media_player.zone_16 #garage
      - media_player.zone_13 #patio
      - media_player.zone_11 #master_bedroom
      - media_player.zone_12 #master_bath
      - media_player.zone_14 #josh_office
      - media_player.zone_15 #cara_office
      - media_player.zone_17 #pool
      - media_player.zone_18 #living_room
    commands:
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room        
      turn_off:
        service: media_player.turn_off
        target:
          entity_id:
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      volume_mute:
        service: media_player.mute
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
      select_source:
        service: media_player.select_source
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          source: "{{ source }}"
      volume_set:
        service: media_player.volume_set
        target:
          entity_id: 
          - media_player.zone_16 #garage
          - media_player.zone_13 #patio
          - media_player.zone_11 #master_bedroom
          - media_player.zone_12 #master_bath
          - media_player.zone_14 #josh_office
          - media_player.zone_15 #cara_office
          - media_player.zone_17 #pool
          - media_player.zone_18 #living_room
        data:
          volume_level: "{{ volume_level }}"
```

**Comment by fin05** [comment]
Sorry about that - You fixed the code or the post?  I do not see any changes to the code?

**Comment by fin05** [comment]
also the entity called media_player.dax_zone_ma does not show in music assistant - only in HA

**Comment by OzGav** [comment]
> Sorry about that - You fixed the code or the post? I do not see any changes to the code?

Just the post

> also the entity called media_player.dax_zone_ma does not show in music assistant - only in HA

So confirm it doesn't show in the list of players like this
![image](https://github.com/music-assistant/hass-music-assistant/assets/19848947/f046cba5-0f5b-47e2-9424-3cd7d7d388d3)

**Comment by fin05** [comment]
correct it is not there - but I need each individual zone to show there - the zones do not show in HA or MA

**Comment by OzGav** [comment]
What do you mean by the zones don't show in HA. Aren't the zones these: `media_player.zone_15`

**Comment by OzGav** [comment]
Also I don't think you are using the universal player properly. I think Marcel might have meant you would have a universal player per zone. I think maybe Marcel was suggesting to recreate the zone wrapped in a universal player. So;
```
  - platform: universal
    name: Dax_Zone_Garage_MA
    unique_id: dax_z_garage_ma
    children:
      - media_player.zone_16 #garage
    commands:
      turn_on:
        service: media_player.turn_on
        target:
          entity_id: 
          - media_player.zone_16 #garage       
      turn_off:
        service: media_player.turn_off
        target:
          entity_id:
          - media_player.zone_16 #garage
      volume_up:
        service: media_player.volume_up
        target:
          entity_id: 
          - media_player.zone_16 #garage
      volume_down:
        service: media_player.volume_down
        target:
          entity_id: 
          - media_player.zone_16 #garage
      volume_mute:
        service: media_player.mute
        target:
          entity_id: 
          - media_player.zone_16 #garage
      select_source:
        service: media_player.select_source
        target:
          entity_id: 
          - media_player.zone_16 #garage
        data:
          source: "{{ source }}"
      volume_set:
        service: media_player.volume_set
        target:
          entity_id: 
          - media_player.zone_16 #garage
        data:
          volume_level: "{{ volume_level }}"
```

Try that, see if the universal player appears in HA and is usable and then see if it appears in MA. Also I am assuming you can see other HA media players in MA
