### ISSUE TITLE
Turning off snapcast group player won't unlink all players

### ISSUE THREAD

**Issue by ronluna** [music-assistant/hass-music-assistant#2107]
### What version of Music Assistant has the issue?

2.0.0b133

### What version of the Home Assistant Integration have you got installed?

n/a

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

If a snapcast group player has more than 4 members, turning off the group player would leave one of the members linked to the first member of the group

### How to reproduce

Create a snapcast group player with over 4 members in it. turn on the group (All members get linked) . Turn off the group (One of the members will remain linked to the first member of that group)

### Music Providers

Spotify

### Player Providers

Snapcast

### Full log output

nothing in the logs

### What version of Home Assistant Core are your running

n/a

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by OzGav** [comment]
So just confirming if there are four or less in the group then everything works ok?

**Comment by ronluna** [comment]
Well I just test with 3 players and same results. So it is safe to say that anything above 2 players won't get completely unlink. 

2 players works as expected!

**Comment by OzGav** [comment]
Explain how you are grouping the players as MA has three ways to do that. You need to supply far more detail.

**Comment by ronluna** [comment]
Apologies for the lack of detail, 

1- Click on the gear icon 
2- Click on the Player tab
3- Click on Add group player
4- Select Snapcast
5- Enter a name for the group player and select the players from the list then save. 
-
Then when the group player is turned on. all the players get automatically linked!
<img width="326" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/9822111/bc08be6f-65c4-4b7d-9155-d243315c4754">

but when the group player is turned off. one of the players remains linked to the group:
<img width="338" alt="image" src="https://github.com/music-assistant/hass-music-assistant/assets/9822111/6df2c332-3125-4c07-aef0-4f604d13237a">

**Comment by SantiagoSotoC** [comment]
@marcelveldt  is this to be solved at the provider level or at the core level?

**Comment by SantiagoSotoC** [comment]
This is a possible solution , [https://github.com/music-assistant/server/pull/1347](https://github.com/music-assistant/server/pull/1347)

**Comment by SantiagoSotoC** [comment]
@ronluna when you can, would you like to test the latest beta, to confirm the solution?

**Comment by ronluna** [comment]
Hello @SantiagoSotoC , Volume control seems to be behaving correctly now, however I did manage to encounter a new bug. Currently MA only allow 2 players to be link at once as seen on this video.


https://github.com/music-assistant/hass-music-assistant/assets/9822111/c5b5a7e1-a646-4930-b7c6-2eddc5816887

and the logs show the following:

```
2024-06-11 22:25:40.313 ERROR (MainThread) [snapcast.control.group] snapclient1 already in group 04cec120-249b-8269-e87b-72fb992eafa2
2024-06-11 22:27:13.521 ERROR (MainThread) [snapcast.control.group] snapclient1 already in group 30d23894-f101-79e9-efb0-084847cee7ed
2024-06-11 22:27:23.153 ERROR (MainThread) [snapcast.control.group] snapclient0#0 already in group 30d23894-f101-79e9-efb0-084847cee7ed
2024-06-11 22:27:23.153 ERROR (MainThread) [snapcast.control.group] snapclient1 already in group 30d23894-f101-79e9-efb0-084847cee7ed
2024-06-11 22:27:31.703 ERROR (MainThread) [snapcast.control.group] snapclient3#3 already in group 30d23894-f101-79e9-efb0-084847cee7ed
2024-06-11 22:27:31.704 ERROR (MainThread) [snapcast.control.group] snapclient0#0 already in group 30d23894-f101-79e9-efb0-084847cee7ed
2024-06-11 22:27:31.704 ERROR (MainThread) [snapcast.control.group] snapclient1 already in group 30d23894-f101-79e9-efb0-084847cee7ed
```

**Comment by SantiagoSotoC** [comment]
@ronluna when you can, would you like to test the latest beta, to confirm the solution?

I'll check tomorrow, I have an idea of what it might be.

**Comment by SantiagoSotoC** [comment]
I'll check tomorrow, I have an idea of what it might be

**Comment by SantiagoSotoC** [comment]
@ronluna  can you test the change in addon dev ?

**Comment by ronluna** [comment]
I've been deploying the beta image using the following stack: 

```
version: "3"
services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:beta # <<< Desired release version here (change beta to latest once there is a stable release)
    container_name: music-assistant-server
    restart: unless-stopped
    # Network mode must be set to host for MA to work correctly
    network_mode: host
    volumes:
      - ${USERDIR:-$HOME}/docker/music-assistant-server/data:/data/
    # privileged caps needed to mount smb folders within the container
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    privileged: true
    environment:
      # Provide logging level as environment variable.
      # default=info, possible=(critical, error, warning, info, debug, verbose)
      - LOG_LEVEL=info
```

I'm not sure how to properly pull and deplay fix_snapcast_player_unsync_when_master_off_2 as I can't find an image for it.

any ideas?
