### ISSUE TITLE
mass.play_media local file playback with announce set to true throws error

### ISSUE THREAD

**Issue by OzGav** [music-assistant/hass-music-assistant#2198]
### What version of Music Assistant has the issue?

2.0.0b145

### What version of the Home Assistant Integration have you got installed?

2024.4.0

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When using a service call and selecting the ANNOUNCE option to true an error is thrown and the queue is cleared. Turning off the option or setting it to false results in correct playback.

### How to reproduce

Use the following service call

```
service: mass.play_media
target:
  entity_id: media_player.ma_picoreplayer
data:
  media_id: countdown
  media_type: track
  announce: true
  use_pre_announce: false
```

### Music Providers

All

### Player Providers

Local

### Full log output

[log.txt](https://github.com/music-assistant/hass-music-assistant/files/15220654/log.txt)

### Additional information

Relevant log lines are:

```
2024-05-06 22:37:51.245 INFO (MainThread) [music_assistant.players] Playback announcement to player piCorePlayer (with pre-announce: False): countdown
2024-05-06 22:37:51.772 ERROR (MainThread) [music_assistant.webserver] Error handling message: players/cmd/play_announcement: Unable to retrieve info for countdown: No such file or directory
```

### What version of Home Assistant Core are your running

2024.5.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
