### ISSUE TITLE
Second TTS is not played if sent while the first TTS is still playing

### ISSUE THREAD

**Issue by nabahr** [music-assistant/hass-music-assistant#2520]
### What version of Music Assistant has the issue?

2.1.0b7

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Any TTS message sent to a speaker while it is currently playing a TTS message is ignored/doesn't play. I would expect that either the new TTS is queued and played next, or maybe even cut off the first message and start playing the second message right away. Queueing and playing both would be my preference.

### How to reproduce

Service call:
```
service: tts.speak
target:
  entity_id: tts.home_assistant_cloud
data:
  media_player_entity_id: media_player.dining_room
  message: I am testing multiple TTS messages
```

Call the service once and the message plays fine, call the service again while the first TTS is still playing and nothing happens. The first TTS will continue playing and the second just disappears.

### Music Providers

N/A

### Player Providers

I have used Chromecast, snapcast, and slimproto. They all have the same issue.

### Full log output

[log.log](https://github.com/user-attachments/files/15929279/log.log)

### Additional information

In the log, I just restarted the server and sent 4 TTS messages back to back to the dining room speaker.

### What version of Home Assistant Core are your running

2024.6.3

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative
