### ISSUE TITLE
Paused playback resumes after TTS

### ISSUE THREAD

**Issue by maxi1134** [music-assistant/hass-music-assistant#2580]
### What version of Music Assistant has the issue?

2.1.0b12

### What version of the Home Assistant Integration have you got installed?

2024.6.2

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When calling the following service on the idle/off group:

```
service: tts.speak
metadata: {}
data:
  cache: true
  media_player_entity_id: media_player.mass_home_group
  message: "{{ message }}"
target:
  entity_id: tts.piper
```

The group does the announcement at the announcement volume level and then starts whatever was playing earlier at the volume of the announcement. Resulting in a cacophonic result sometimes early in the morning.

Issuing the command while the group is already playing results in perfect handling;
Volume goes up
Announcement is done
Volume goes down
Music restarts

This issue only seems to happen when the group is not playing anything initially.

### How to reproduce

Turn off the group and play an announcement

### Music Providers

Spotify
Filesystem SMB

### Player Providers

Chromecast 
Chromecast Group `(This is where this issue happens)`

### Full log output

[lo.log](https://github.com/user-attachments/files/16116807/lo.log)

### Additional information

The TTS is started from HA 

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
