### ISSUE TITLE
Not all TuneIn stations available in MA

### ISSUE THREAD

**Issue by dinki** [music-assistant/hass-music-assistant#2683]
### What version of Music Assistant has the issue?

2.1.0

### What version of the Home Assistant Integration have you got installed?

2024.7.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

The ONE radio station I'd like to play in our area is not showing up in my radio list but it is available on TuneIn as I listen to it daily on Alexa.  I did find it (can't remember how) in MA and have this that plays it:

```
      - service: mass.play_media
        target:
          entity_id: "{{ target_mediaplayer_device }}"
        data:
          media_id: tunein://radio/s34824--aac
        enabled: true
```
I'm just curious why it doesn't show up in my default list.  Playing it this way does not get me coverart.  I know this is minor it's just odd.

It does show up in my list on Tune In site:

![image](https://github.com/user-attachments/assets/e7596b84-dad7-4bf8-aed6-bb911c1f36f5)

Note that this is a free station and not premium.

### How to reproduce

Go to my TuneIn channels and look for Big 102.1

### Music Providers

TuneIn

### Player Providers

Home Assistant

### Full log output

NA

### What version of Home Assistant Core are your running

2024.7.1

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)
