### ISSUE TITLE
Player Groups Included In Themselves when Managing with Home Assistant Automations

### ISSUE THREAD

**Issue by AeroSteveO** [music-assistant/hass-music-assistant#2941]
### What version of Music Assistant has the issue?

2.3.0b25 

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

When trying to manage the player groups with home assistant automations, i end up with my "all players" group containing itself, then when trying to play to that group, an error is output from Music Assistant. Restarting music assistant can help clear the recursive group temporarily but the moment my automations start messing with the groups again, it stops working. 

### How to reproduce

Create a Player Group (squeezelite or air play are what i've seen it on)
Add two speakers to the group
Using the home assistant "media player: unjoin" action, unjoin the players from the group
Using the home assistant "media player: join" action, join the players back to the group

### Music Providers

Plex

### Player Providers

squeezelite and air play groups/players (using devices running squeezelite-esp32)

### Full log output

[music-assistant.log](https://github.com/user-attachments/files/17050942/music-assistant.log)

### Additional information

the following HA script is what i run prior to sending the play music action

```
ensure_media_players_on:
  alias: Ensure Media Players On
  sequence:
  - choose:
    - conditions:
      - condition: device
        device_id: 612b88eb447e3217264c040dc54e56cb
        domain: media_player
        entity_id: 2af2f85f48833ef3d9625dfe9dea712e
        type: is_off
      sequence:
      - action: media_player.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
          - media_player.all_airplay
          - media_player.esp32_airplay_ed8c0
          - media_player.esp32_airplay_edbc0
      - action: media_player.join
        metadata: {}
        data:
          group_members:
          - media_player.esp32_airplay_ed8c0
          - media_player.esp32_airplay_edbc0
        target:
          entity_id: media_player.all_airplay
  description: ''
```

and the following is my stop action for stopping all playback

```
- id: '1726609945286'
  alias: Media Button Actions
  description: ''
  trigger:
  - type: turned_on
    platform: device
    device_id: 40aac210ebcaedc9deca0d0820c8ed99
    entity_id: 49a356a8801cc19a121011388bf9616f
    domain: binary_sensor
    id: Stop
  - type: turned_on
    platform: device
    device_id: 40aac210ebcaedc9deca0d0820c8ed99
    entity_id: 3f9511feb3c7f05b2555df3647e61756
    domain: binary_sensor
    id: Restart
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Stop
      sequence:
      - action: media_player.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
          - media_player.all_airplay
          - media_player.esp32_airplay_ed8c0
          - media_player.esp32_airplay_edbc0
      - action: media_player.unjoin
        metadata: {}
        data: {}
        target:
          entity_id:
          - media_player.all_airplay
          - media_player.esp32_airplay_ed8c0
          - media_player.esp32_airplay_edbc0
    - conditions:
      - condition: trigger
        id:
        - Restart
      sequence:
      - action: hassio.addon_restart
        metadata: {}
        data:
          addon: d5369777_music_assistant_beta
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 72
        target:
          entity_id: light.esphome_web_757c70_key_2_light
  mode: single

```

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant Supervised

### On what type of hardware are you running?

Linux
