### ISSUE TITLE
Memory leak in Docker image

### ISSUE THREAD

**Issue by bardahlm** [music-assistant/hass-music-assistant#2954]
### What version of Music Assistant has the issue?

2.2.5

### What version of the Home Assistant Integration have you got installed?

2024.9.1

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

I added the Monitor Docker integration and noticed that the Music Assistant Docker instance leak memory, about 15 MB per minute.

![image](https://github.com/user-attachments/assets/5dffa2ed-7162-4b7c-867b-6534e45e7904)

I'm currently not using Music Assistant much, I have Squeezebox radio added as a player and a misconfigured Spotify music provider.

When left alone the container used over 2 Gb in just a few hours.

### How to reproduce

Unsure. Install music assistant as a Docker container and monitor memory usage, for example using the HA addon "Monitor Docker".

### Music Providers

Spotify, not sure if this one is trigging the leak.

### Player Providers

Squeezebox

### What version of Home Assistant Core are your running

2024.9.2

### What type of installation are you running?

Home Assistant Container

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by bardahlm** [comment]
[music-assistant.log](https://github.com/user-attachments/files/17090480/music-assistant.log)
Log file

**Comment by marcelveldt** [comment]
You are the only one reporting this. Also I cant reproduce. I wonder if its because of the misconfigured spotify provider.
Can you either try to remove that provider from the settings or set it up correctly ?

**Comment by bardahlm** [comment]
I've configured Spotify and played some music. Still leaks memory.

![image](https://github.com/user-attachments/assets/93a0b2eb-3e3b-4b37-9c80-245f40cd53cb)

Container started with docker compose:

```
services:
  musicassistant:
    image: ghcr.io/music-assistant/server
    domainname: docker.example.com
    hostname: ma
    restart: unless-stopped
    container_name: musicassistant
    volumes:
      - /home/user/ma:/data
    networks:
      ha:
        ipv6_address: 2001:db8::8
        ipv4_address: 192.168.88.37
    privileged: true
    mem_limit: 250mb # set to avoid the cointainer growing and allocation all memory

networks:
  ha:
    name: my-macvlan-net
    external: true
```
Is it possible to use tracemalloc or some other python tools to find the leak?
