### ISSUE TITLE
media_player.join not working

### ISSUE THREAD

**Issue by JDogg016** [music-assistant/hass-music-assistant#3134]
### What version of Music Assistant has the issue?

2.3.2

### What version of the Home Assistant Integration have you got installed?

2024.10.4

### Have you tried everything in the Troubleshooting FAQ and reviewed the Open and Closed Issues and Discussions to resolve this yourself?

- [X] Yes

### The problem

Running the action to join two Sonos MA Speakers has no effect:

```
action: media_player.join
data:
  group_members:
    - media_player.ma_gym_overhead_speaker_sonos
    - media_player.ma_gym_tv_speaker_sonos
target:
  entity_id: media_player.ma_gym_tv_speaker_sonos
```

### How to reproduce

Just try to run an action to join Sonos speakers in HA (or through Node Red).

### Music Providers

N/A

### Player Providers

Sonos

### What version of Home Assistant Core are your running

2024.10.4

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Raspberry Pi
