### ISSUE TITLE
artwork issue when playing via service

### ISSUE THREAD

**Issue by zala143** [music-assistant/hass-music-assistant#446]
Having an issue displaying artwork on a regular HA dashboard card (custom:mini-media-player) when playing music in a particular scenario.

First off, this is such great project, thank you..

I have a good working solution, with a few media player types tested/working - when using the standard Music Assistant interface to play music, all is working; also displays media artwork on regular HA dashboard cards (custom:mini-media-player).

However, if I play media to the media_player.mass_xxx entity via a service (example below) then the music plays just fine but the artwork never shows on the HA dashboard card.

I would love to solve this issue and hopefully its something I'm not doing correctly - my use case is that that example service below is being called by a Music Tag scanning blueprint to play music when NFC tags are scanned - works great except for the artwork in played via a media_player.mass_xxx entity.  

Thanks in advance.

Example Service 
```
service: media_player.play_media
data:
  media_content_id: https://open.spotify.com/album/6DN7GcZF1HywzrkGN6Eeqk
  media_content_type: music
  enqueue: play
target:
  entity_id: media_player.mass_up2stream_01
```
