### ISSUE TITLE
No cloud.tts through 'mass' sonos...

### ISSUE THREAD

**Issue by fribse** [music-assistant/hass-music-assistant#878]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I have set up all our google home, sonos etc. as 'mass' media players.
If send a 'tts.cloud_say" to the sonos 'directly' ie. not throught the mass, the text is said as it should.
If I send it to the same sonos, but as the mass media player, nothing is said.

### How to reproduce

Developer tools:
  Service:Text-to-Speech (TTS): Say an TTS message with cloud
  Entity: media_player.mass_kokken
  Message: "Test test testesen"

### What version of Home Assistant Core are your running

2022.8.6

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Generic x86-64 (e.g. Intel NUC)

**Comment by marcelveldt** [comment]
Can you try to turn ON the player first ? I believe we have a small bug where the player needs to be in ON state before tts works.

**Comment by fribse** [comment]
Hi @marcelveldt 
So, turning it on, just by playing audio to it, or some other thing?

**Comment by fribse** [comment]
I tried with the 'media_player.turn_on' also, and also with 'media_player.set_volume' in an automation before the tts.

**Comment by marcelveldt** [comment]
> I tried with the 'media_player.turn_on' also, and also with 'media_player.set_volume' in an automation before the tts.

OK and did that make any difference ?

**Comment by fribse** [comment]
Sorry, no, no change, it's really weird. Yesterday all of the sudden a single message came through, very very odd.

**Comment by gieljnssns** [comment]
It isn't only with `tts.cloud_say`
This doesn't work to
```
service: tts.voicerss_say
data:
  message: Blijven proberen
  entity_id: media_player.mass_keuken
```
This works
```
service: tts.voicerss_say
data:
  message: Blijven proberen
  entity_id: media_player.keuken
```
