### ISSUE TITLE
Playlist doesn't load properly

### ISSUE THREAD

**Issue by marcin-adamczewski** [music-assistant/hass-music-assistant#937]
### What version of Music Assistant has the issue?

2022.8.4

### The problem

I'm trying to run simple automation that starts a playlist from Spotify on my Google Home speaker. The result is that music starts but the playlist queue composes of some random songs, usually the ones that I've listened to before.
When playing the same playlist through Music Assistant panel it works fine. I tried to pass media_content_type both as music and playlist but no luck.

### How to reproduce

Here is the HA script that I use. To reproduce you'd need to change entity_id for your speaker.

```yaml
alias: Play Spotify Playlist Bathroom Test
sequence:
  - service: media_player.play_media
    data:
      media_content_id: >-
        https://open.spotify.com/playlist/59ceWQQTG6TPUUIKq7StUi?si=a6d1622d2b914845
      media_content_type: playlist
    target:
      entity_id: media_player.mass_googlehome7958
mode: single
icon: mdi:spotify
```

### What version of Home Assistant Core are your running

2022.10.1

### What type of installation are you running?

Home Assistant OS

### On what type of hardware are you running?

Alternative

**Comment by erkr** [comment]
@marcin-adamczewski 
Please have a look here: https://github.com/music-assistant/hass-music-assistant/discussions/834

**Comment by marcin-adamczewski** [comment]
Thank you for pointing me to the thread.
I'm not sure if I should continue the discussion in the thread or keep this issue open as the proposed solution doesn't work for me.

Anyways, I updated my script so it looks like this

```yaml
alias: Play Spotify Playlist Bathroom Test
sequence:
  - service: media_player.play_media
    data:
      media_content_id: media-source://mass/database://playlist/15
      media_content_type: playlist
    target:
      entity_id: media_player.mass_googlehome7958
mode: single
icon: mdi:spotify

```

The playlist starts but it contains some random number of songs like 120 or 180 instead of the 15 I have in my playlist. I'm not sure if Spotify adds those songs to the queue but shuffling such playlist with songs I don't want to listen to is not nice :/

**Comment by OzGav** [comment]
Spotify doesn’t add songs to the queue. MA adds the songs to the queue. It sounds like you need to clear the queue first.

**Comment by marcin-adamczewski** [comment]
@OzGav Bingo! Clearing the queue worked. So now to be sure I always clear the queue before starting a playlist.
Updated script looks like this:

```yml
alias: Play Spotify Playlist Bathroom Test
sequence:
  - service: mass.queue_command
    data:
      command: clear
    target:
      entity_id: media_player.mass_googlehome7958
  - service: media_player.play_media
    data:
      media_content_id: media-source://mass/database://playlist/15
      media_content_type: playlist
    target:
      entity_id: media_player.mass_googlehome7958
mode: single
icon: mdi:spotify
```

Thank you guys for your help!
